<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Autom%C3%B3veis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
!pip install tensorflow

In [45]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [2]:
# Importando as bibliotecas que serão utilizadas
import pandas as pd
import tensorflow as tf      # Deep Learning
import sklearn               # Machine Learnin

In [3]:
base = pd.read_csv('autos.csv' , encoding = 'ISO-8859-1')
base


,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0.0,70435.0,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300.0,test,coupe,2011.0,manuell,190.0,NaN,125000.0,5.0,diesel,audi,ja,2016-03-24 00:00:00,0.0,66954.0,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,NaN,2016-03-14 00:00:00,0.0,90480.0,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500.0,test,kleinwagen,2001.0,manuell,75.0,golf,150000.0,6.0,benzin,volkswagen,nein,2016-03-17 00:00:00,0.0,91074.0,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600.0,test,kleinwagen,2008.0,manuell,69.0,fabia,90000.0,7.0,diesel,skoda,nein,2016-03-31 00:00:00,0.0,60437.0,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125188,2016-03-19 18:52:38,SEAT_Ibiza_1.4L_16V_Bj.2003_TÜV8/16_silber_TÜV...,privat,Angebot,3200.0,test,kleinwagen,2003.0,manuell,75.0,ibiza,150000.0,8.0,benzin,seat,nein,2016-03-19 00:00:00,0.0,40880.0,2016-04-07 06:16:40
125189,2016-03-28 20:50:53,Octavia_Avant_2.0_TDI_RS,privat,Angebot,2990.0,control,kombi,2008.0,NaN,0.0,octavia,150000.0,10.0,diesel,skoda,nein,2016-03-28 00:00:00,0.0,50737.0,2016-03-28 20:50:53
125190,2016-03-20 00:57:46,Volkswagen_Passat_Variant_2.0_TDI_DPF_Sportline,privat,Angebot,9250.0,control,kombi,2008.0,manuell,170.0,passat,150000.0,5.0,diesel,volkswagen,nein,2016-03-19 00:00:00,0.0,90489.0,2016-04-06 03:16:26
125191,2016-03-25 15:56:09,Volkswagen_Passat_Variant_2.0_Pacific,privat,Angebot,650.0,test,kombi,1996.0,manuell,116.0,passat,150000.0,12.0,benzin,volkswagen,nein,2016-03-25 00:00:00,0.0,49828.0,2016-04-06 20:16:56


In [4]:
# Remoção dos atributos que não irão influenciar em prever o preço
base = base.drop('dateCrawled', axis = 1)
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)
base

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,Golf_3_1.6,privat,Angebot,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN
1,A5_Sportback_2.7_Tdi,privat,Angebot,18300.0,test,coupe,2011.0,manuell,190.0,NaN,125000.0,5.0,diesel,audi,ja
2,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,NaN
3,GOLF_4_1_4__3TÜRER,privat,Angebot,1500.0,test,kleinwagen,2001.0,manuell,75.0,golf,150000.0,6.0,benzin,volkswagen,nein
4,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600.0,test,kleinwagen,2008.0,manuell,69.0,fabia,90000.0,7.0,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125188,SEAT_Ibiza_1.4L_16V_Bj.2003_TÜV8/16_silber_TÜV...,privat,Angebot,3200.0,test,kleinwagen,2003.0,manuell,75.0,ibiza,150000.0,8.0,benzin,seat,nein
125189,Octavia_Avant_2.0_TDI_RS,privat,Angebot,2990.0,control,kombi,2008.0,NaN,0.0,octavia,150000.0,10.0,diesel,skoda,nein
125190,Volkswagen_Passat_Variant_2.0_TDI_DPF_Sportline,privat,Angebot,9250.0,control,kombi,2008.0,manuell,170.0,passat,150000.0,5.0,diesel,volkswagen,nein
125191,Volkswagen_Passat_Variant_2.0_Pacific,privat,Angebot,650.0,test,kombi,1996.0,manuell,116.0,passat,150000.0,12.0,benzin,volkswagen,nein


In [5]:
base['name'].value_counts()

,count
name,
Ford_Fiesta,232
Volkswagen_Golf_1.4,225
BMW_318i,214
Opel_Corsa,199
BMW_316i,190
...,...
Volkswagen_Polo_1.4_Comfortline_1_Hand_scheckheftgepflegt,1
Mercedes_Benz_200E_W124_1Hd__135tkm_original,1
Opel_Kadett_C_City__Scheunenfund__abgemeldet_seit_1993,1


In [6]:
# removendo a coluna name pq ela possui valores unicos
base = base.drop('name', axis = 1)

In [7]:
base['seller'].value_counts()

,count
seller,
privat,125192
gewerblich,1


In [8]:
base = base.drop('seller', axis = 1)

In [9]:
base['offerType'].value_counts()

,count
offerType,
Angebot,125190
Gesuch,2
Angebo,1


In [10]:
base = base.drop('offerType', axis = 1)

In [11]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN
1,18300.0,test,coupe,2011.0,manuell,190.0,NaN,125000.0,5.0,diesel,audi,ja
2,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,NaN
3,1500.0,test,kleinwagen,2001.0,manuell,75.0,golf,150000.0,6.0,benzin,volkswagen,nein
4,3600.0,test,kleinwagen,2008.0,manuell,69.0,fabia,90000.0,7.0,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
125188,3200.0,test,kleinwagen,2003.0,manuell,75.0,ibiza,150000.0,8.0,benzin,seat,nein
125189,2990.0,control,kombi,2008.0,NaN,0.0,octavia,150000.0,10.0,diesel,skoda,nein
125190,9250.0,control,kombi,2008.0,manuell,170.0,passat,150000.0,5.0,diesel,volkswagen,nein
125191,650.0,test,kombi,1996.0,manuell,116.0,passat,150000.0,12.0,benzin,volkswagen,nein


In [12]:
base.loc[base['price'] <= 10]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0.0,test,limousine,1980.0,manuell,50.0,andere,40000.0,7.0,benzin,volkswagen,nein
40,0.0,test,NaN,1990.0,NaN,0.0,corsa,150000.0,1.0,benzin,opel,NaN
60,1.0,control,suv,1994.0,manuell,286.0,NaN,150000.0,11.0,NaN,sonstige_autos,NaN
91,1.0,control,limousine,1995.0,manuell,113.0,e_klasse,150000.0,4.0,diesel,mercedes_benz,nein
115,0.0,test,NaN,2017.0,manuell,0.0,golf,5000.0,12.0,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125125,0.0,control,NaN,2000.0,NaN,0.0,NaN,5000.0,0.0,NaN,mazda,NaN
125127,0.0,control,kombi,2008.0,manuell,140.0,astra,90000.0,0.0,benzin,opel,nein
125151,0.0,control,kleinwagen,2003.0,manuell,60.0,ka,125000.0,2.0,benzin,ford,ja
125159,0.0,control,kombi,1996.0,NaN,0.0,NaN,5000.0,0.0,NaN,volkswagen,NaN


In [13]:
base['price'].mean()

np.float64(10741.025209278549)

In [14]:
base.shape

(125193, 12)

In [15]:
base.loc[base['price'] > 350000]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000.0,control,coupe,1980.0,manuell,277.0,andere,20000.0,12.0,benzin,bmw,nein
10649,420000.0,control,coupe,2004.0,manuell,483.0,911,50000.0,4.0,benzin,porsche,nein
14663,11111111.0,control,coupe,2003.0,manuell,64.0,polo,150000.0,2.0,benzin,volkswagen,NaN
16889,1000000.0,control,kombi,1998.0,NaN,0.0,mondeo,150000.0,0.0,benzin,ford,ja
20143,1250000.0,test,coupe,2016.0,manuell,500.0,911,5000.0,3.0,benzin,porsche,nein
20746,12345678.0,test,NaN,1995.0,NaN,0.0,NaN,150000.0,0.0,NaN,volkswagen,NaN
21467,9999999.0,control,coupe,1967.0,manuell,215.0,911,50000.0,10.0,benzin,porsche,nein
26327,600000.0,test,coupe,2016.0,manuell,500.0,911,5000.0,3.0,benzin,porsche,nein
38445,999999.0,test,bus,1981.0,manuell,70.0,transporter,150000.0,1.0,benzin,volkswagen,NaN
39625,12345678.0,control,NaN,2018.0,manuell,95.0,v40,150000.0,6.0,NaN,volvo,nein


In [16]:
base.shape

(125193, 12)

In [17]:
base.loc[pd.isnull(base['vehicleType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN
16,300.0,test,NaN,2016.0,NaN,60.0,polo,150000.0,0.0,benzin,volkswagen,NaN
22,2900.0,test,NaN,2018.0,manuell,90.0,meriva,150000.0,5.0,benzin,opel,nein
26,5555.0,control,NaN,2017.0,manuell,125.0,c4,125000.0,4.0,NaN,citroen,nein
31,899.0,control,NaN,2016.0,manuell,60.0,clio,150000.0,6.0,benzin,renault,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125131,300.0,control,NaN,2017.0,NaN,0.0,focus,150000.0,0.0,NaN,ford,ja
125144,999.0,test,NaN,2017.0,manuell,101.0,a3,150000.0,4.0,benzin,audi,NaN
125154,31499.0,test,NaN,2018.0,manuell,300.0,golf,20000.0,3.0,NaN,volkswagen,nein
125170,0.0,test,NaN,1980.0,NaN,0.0,andere,60000.0,0.0,NaN,chevrolet,nein


In [18]:
base['vehicleType'].mode()

,vehicleType
0,limousine


In [19]:
base.loc[pd.isnull(base['gearbox'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450.0,test,kleinwagen,1910.0,NaN,0.0,ka,5000.0,0.0,benzin,ford,NaN
16,300.0,test,NaN,2016.0,NaN,60.0,polo,150000.0,0.0,benzin,volkswagen,NaN
32,245.0,test,limousine,1994.0,NaN,0.0,golf,150000.0,2.0,benzin,volkswagen,nein
37,1500.0,test,NaN,2016.0,NaN,0.0,kangoo,150000.0,1.0,diesel,renault,nein
40,0.0,test,NaN,1990.0,NaN,0.0,corsa,150000.0,1.0,benzin,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125131,300.0,control,NaN,2017.0,NaN,0.0,focus,150000.0,0.0,NaN,ford,ja
125159,0.0,control,kombi,1996.0,NaN,0.0,NaN,5000.0,0.0,NaN,volkswagen,NaN
125170,0.0,test,NaN,1980.0,NaN,0.0,andere,60000.0,0.0,NaN,chevrolet,nein
125189,2990.0,control,kombi,2008.0,NaN,0.0,octavia,150000.0,10.0,diesel,skoda,nein


In [20]:
base['gearbox'].value_counts()

,count
gearbox,
manuell,92585
automatik,25815


In [21]:
base.loc[pd.isnull(base['model'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300.0,test,coupe,2011.0,manuell,190.0,NaN,125000.0,5.0,diesel,audi,ja
60,1.0,control,suv,1994.0,manuell,286.0,NaN,150000.0,11.0,NaN,sonstige_autos,NaN
83,350.0,control,kleinwagen,1997.0,manuell,54.0,NaN,150000.0,3.0,NaN,fiat,ja
119,0.0,test,kleinwagen,1999.0,NaN,0.0,NaN,5000.0,0.0,benzin,volkswagen,NaN
139,1450.0,control,limousine,1992.0,manuell,136.0,NaN,150000.0,0.0,NaN,audi,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
125125,0.0,control,NaN,2000.0,NaN,0.0,NaN,5000.0,0.0,NaN,mazda,NaN
125147,2599.0,test,limousine,1979.0,automatik,116.0,NaN,125000.0,9.0,benzin,opel,nein
125159,0.0,control,kombi,1996.0,NaN,0.0,NaN,5000.0,0.0,NaN,volkswagen,NaN
125164,1800.0,test,kleinwagen,1964.0,manuell,0.0,NaN,150000.0,2.0,benzin,audi,NaN


In [22]:
base.loc[pd.isnull(base['fuelType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999.0,test,kleinwagen,1998.0,manuell,101.0,golf,150000.0,0.0,NaN,volkswagen,NaN
13,2500.0,control,kombi,2004.0,manuell,131.0,passat,150000.0,2.0,NaN,volkswagen,nein
26,5555.0,control,NaN,2017.0,manuell,125.0,c4,125000.0,4.0,NaN,citroen,nein
36,1600.0,control,andere,1991.0,manuell,75.0,kadett,70000.0,0.0,NaN,opel,NaN
41,7500.0,control,limousine,2002.0,automatik,306.0,e_klasse,150000.0,4.0,NaN,mercedes_benz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125148,4200.0,test,limousine,2003.0,manuell,143.0,3er,150000.0,5.0,NaN,bmw,nein
125154,31499.0,test,NaN,2018.0,manuell,300.0,golf,20000.0,3.0,NaN,volkswagen,nein
125159,0.0,control,kombi,1996.0,NaN,0.0,NaN,5000.0,0.0,NaN,volkswagen,NaN
125170,0.0,test,NaN,1980.0,NaN,0.0,andere,60000.0,0.0,NaN,chevrolet,nein


In [23]:
base['fuelType'].value_counts()

,count
fuelType,
benzin,75493
diesel,36233
lpg,1778
cng,198
hybrid,98
andere,71
elektro,44


In [24]:
base.loc[pd.isnull(base['notRepairedDamage'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480.0,test,NaN,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,NaN
2,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,NaN
8,14500.0,control,bus,2014.0,manuell,125.0,c_max,30000.0,8.0,benzin,ford,NaN
9,999.0,test,kleinwagen,1998.0,manuell,101.0,golf,150000.0,0.0,NaN,volkswagen,NaN
12,999.0,control,kombi,1995.0,manuell,115.0,passat,150000.0,11.0,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125174,9500.0,test,suv,1972.0,manuell,75.0,andere,80000.0,5.0,benzin,jeep,NaN
125183,900.0,control,coupe,1998.0,manuell,102.0,3er,150000.0,6.0,benzin,bmw,NaN
125184,600.0,test,kombi,2002.0,manuell,101.0,vectra,150000.0,4.0,diesel,opel,NaN
125185,6200.0,test,coupe,2004.0,automatik,150.0,3er,150000.0,10.0,diesel,bmw,NaN


In [25]:
base['notRepairedDamage'].value_counts()

,count
notRepairedDamage,
nein,88684
ja,12239


In [26]:
valores = {'vehicleType': 'limousine',
           'gearbox': 'manuell',
           'model': 'golf',
           'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}

In [27]:
base = base.fillna(value = valores)

In [28]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480.0,test,limousine,1993.0,manuell,0.0,golf,150000.0,0.0,benzin,volkswagen,nein
1,18300.0,test,coupe,2011.0,manuell,190.0,golf,125000.0,5.0,diesel,audi,ja
2,9800.0,test,suv,2004.0,automatik,163.0,grand,125000.0,8.0,diesel,jeep,nein
3,1500.0,test,kleinwagen,2001.0,manuell,75.0,golf,150000.0,6.0,benzin,volkswagen,nein
4,3600.0,test,kleinwagen,2008.0,manuell,69.0,fabia,90000.0,7.0,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
125188,3200.0,test,kleinwagen,2003.0,manuell,75.0,ibiza,150000.0,8.0,benzin,seat,nein
125189,2990.0,control,kombi,2008.0,manuell,0.0,octavia,150000.0,10.0,diesel,skoda,nein
125190,9250.0,control,kombi,2008.0,manuell,170.0,passat,150000.0,5.0,diesel,volkswagen,nein
125191,650.0,test,kombi,1996.0,manuell,116.0,passat,150000.0,12.0,benzin,volkswagen,nein


In [29]:
base.isnull().sum()

,0
price,1
abtest,1
vehicleType,0
yearOfRegistration,1
gearbox,0
powerPS,1
model,0
kilometer,1
monthOfRegistration,1
fuelType,0


In [30]:
base.columns

Index(['price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'notRepairedDamage'],
      dtype='object')

In [31]:
X = base.iloc[:, 1:12].values # Atributos previsores
X

array([['test', 'limousine', 1993.0, ..., 'benzin', 'volkswagen', 'nein'],
       ['test', 'coupe', 2011.0, ..., 'diesel', 'audi', 'ja'],
       ['test', 'suv', 2004.0, ..., 'diesel', 'jeep', 'nein'],
       ...,
       ['control', 'kombi', 2008.0, ..., 'diesel', 'volkswagen', 'nein'],
       ['test', 'kombi', 1996.0, ..., 'benzin', 'volkswagen', 'nein'],
       [nan, 'limousine', nan, ..., 'benzin', nan, 'nein']], dtype=object)

In [32]:
y = base.iloc[:, 0].values # Atributo classe
y

array([  480., 18300.,  9800., ...,  9250.,   650.,    nan])

In [33]:
base['brand'].value_counts()

,count
brand,
volkswagen,26742
bmw,13597
opel,13434
mercedes_benz,11894
audi,10939
ford,8683
renault,6091
peugeot,3735
fiat,3216


In [34]:
base.columns

Index(['price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'notRepairedDamage'],
      dtype='object')

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(),
                                                 [0, 1, 3, 5, 8, 9, 10] # Índices das colunas categóricas
                                                 )],
                                  remainder='passthrough' # Mantém as colunas que não foram transformadas
                                  )

In [39]:
X = onehotencoder.fit_transform(X).toarray()
X

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.70e+02, 1.50e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.16e+02, 1.50e+05, 1.20e+01],
       [0.00e+00, 0.00e+00, 1.00e+00, ...,      nan,      nan,      nan]])

In [40]:
base.shape

(125193, 12)

In [41]:
X.shape

(125193, 316)

In [42]:
(316 + 1) / 2

158.5

In [46]:
regressor = Sequential([
    tf.keras.layers.InputLayer(shape = (316,)), # 316 colunas
    tf.keras.layers.Dense(units = 158, activation = 'relu'), # 316 + 1 / 2 = 158
    tf.keras.layers.Dense(units = 158, activation = 'relu'),
    tf.keras.layers.Dense(units = 1, activation = 'linear')
])

In [47]:
regressor.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 158)            │        50,086 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 158)            │        25,122 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           159 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 75,367 (294.40 KB)

 Trainable params: 75,367 (294.40 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
12000 - 13000, 11500 - 10000
(abs(12000 - 13000) + abs(11500 - 10000)) / 2

1250.0

In [56]:
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')
regressor.fit(X, y, batch_size = 300, epochs = 100)

Epoch 1/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: nan
Epoch 2/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 3/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 4/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: nan
Epoch 5/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 6/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 7/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 8/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 9/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: nan
Epoch 10/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 11/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: nan
Epoch 12/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 13/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: nan
Epoch 14/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: nan
Epoch 15/100
418/418 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: nan
Epoch 16/100
418/41

In [50]:
X.shape

(125193, 316)

In [51]:
previsoes = regressor.predict(X) # Utilizando os dados para prever

3913/3913 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step


In [52]:
previsoes

array([[5764.7656],
       [4824.4526],
       [4823.0674],
       ...,
       [5770.2227],
       [5767.3726],
       [      nan]], dtype=float32)

In [53]:
y

array([  480., 18300.,  9800., ...,  9250.,   650.,    nan])

In [54]:
y.mean()

np.float64(nan)

In [55]:
previsoes.mean()

np.float32(nan)