<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Operations_on_tensor_Aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
#Multiplicação
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) # criação de um tensor 2D chamado x com duas linhas e 4 colunas

In [4]:
print(x.shape)

torch.Size([2, 4])


In [28]:
x*10 #multiplicando cada elemento por 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [6]:
#Soma
x.add(10) #adicionamos 10 a cada elemento de x

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

### Remodelar

### Existem várias maneiras de remodelar um tensor.

In [9]:
#1) Visualizar
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [10]:
x.shape

torch.Size([2, 4])

In [11]:
x.view(4,2) #remodelamos x de um tensor 2x4 para um tensor 4x2

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

### Ao remodelar o tensor, precisamos ter em mente que o número de elementos em seu interior deve permanecer o mesmo; por exemplo, se tínhamos 8 elementos no total, as possíveis formas para as quais ele pode ser convertido também devem conter 8 elementos.

In [12]:
x.view(8,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

### 2) Espremer

### No `squeeze`, fornecemos o índice do eixo que queremos remover, o qual possui apenas um item nessa dimensão.



In [14]:
a = torch.ones(2,1,10) #Criamos um tensor chamado a com formato 2x1x10 e comprimimos a primeira dimensão

In [16]:
#Este é um tensor composto por duas pilhas, cada uma com uma linha e 10 colunas, totalizando 20 elementos
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [20]:
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.squeeze(1)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 1, 10])
Este é o formato depois de apertar torch.Size([2, 10])


### Como você pode ver, removemos o primeiro índice do eixo, que contém apenas um item. Se o eixo tiver mais de um item, ele não será removido.

In [21]:
a = torch.ones(2,2,10)
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.squeeze(1)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 2, 10])
Este é o formato depois de apertar torch.Size([2, 2, 10])


In [22]:
a = torch.ones(2,3,1)
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.squeeze(2)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 3, 1])
Este é o formato depois de apertar torch.Size([2, 3])


### 3) soltar
### É o exato oposto de *squeeze*: em vez de remover, estamos adicionando uma dimensão ao nosso tensor.

In [23]:
a = torch.ones(2,3)
print(f"Este é o formato antes de apertar {a.shape}")
unsqueezed = a.unsqueeze(2)
print(f"Este é o formato depois de apertar {unsqueezed.shape}")

Este é o formato antes de apertar torch.Size([2, 3])
Este é o formato depois de apertar torch.Size([2, 3, 1])


### Indexação [None]: uma abordagem muito comum

In [24]:
a = torch.ones(2,3)

In [27]:
#Adicionar "none" criaria automaticamente uma dimensão fictícia no eixo especificado:
print(a[None].shape)# eixo fictício no índice 0
print(a[:,None].shape)#eixo fictício no índice 1
print(a[:,:,None].shape)#eixo fictício no índice 2

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


### em visão computacional, tenha em mente que o formato do tensor seria:

#### (número total de elementos)para tensor 1D
#### (linhas e colunas) para tensor 2D
#### (número de canais, linhas e colunas) para tensor 3D
#### (tamanho do lote, número de canais, linhas e colunas) para tensor 4D