<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Tensor_Operations__Pr%C3%A1tica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

In [8]:
#Criação de tensor 1D
tensor_1d = torch.tensor([25, 30, 35])
tensor_1d.shape

torch.Size([3])

In [9]:
#Criação de tensor 2D
tensor_2d = torch.tensor([[5, 15],
                          [20, 25],
                          [30, 35]])
tensor_2d.shape

torch.Size([3, 2])

In [10]:
#Criação do tensor 3D
tensor_3d = torch.tensor([[[2, 4], [6, 8]],
                          [[10, 12], [14, 16]]])
tensor_3d.shape

torch.Size([2, 2, 2])

In [12]:
#Multiplica os elementos por 5
multi_escalar = tensor_2d*5
multi_escalar

tensor([[ 25,  75],
        [100, 125],
        [150, 175]])

In [17]:
#Soma dos elementos
soma_tensor = tensor_2d.add(5)
soma_tensor

tensor([[10, 20],
        [25, 30],
        [35, 40]])

In [18]:
#visualização do tensor 2d
tensor_2d

tensor([[ 5, 15],
        [20, 25],
        [30, 35]])

In [19]:
#Remodelagem
mold_tensor = tensor_2d.view(2,3)
mold_tensor

tensor([[ 5, 15, 20],
        [25, 30, 35]])

In [20]:
#criando um tensor com dimensões para testar o squeeze
dim_tensor = torch.ones(1, 3, 1)
dim_tensor

tensor([[[1.],
         [1.],
         [1.]]])

In [24]:
#Removendo dimensões de tamanho 1
tam_tensor = dim_tensor.squeeze(0).squeeze(1)
tam_tensor.shape

torch.Size([3])

In [25]:
unsquze_tensor = tam_tensor.unsqueeze(1)
unsquze_tensor.shape
tam_tensor[:, None].shape

torch.Size([3, 1])

In [26]:
#Definindo matriz A de dimensões e matriz B de dimensões
matriz_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

matriz_b = torch.tensor([[10, 20, 30, 40],
                         [50, 60, 70, 80]])

In [27]:
#Multiplicação de matriz
matriz_result = torch.matmul(matriz_a, matriz_b)
matriz_result
matriz_result.shape

torch.Size([3, 4])

In [29]:
#Simulando imagem
imagem_tensor = torch.rand(3, 15, 10)
imagem_tensor.shape

torch.Size([3, 15, 10])

In [30]:
#alteração de ordem dos eixos
eixo_tensor = imagem_tensor.permute(1, 2, 0)
eixo_tensor.shape

torch.Size([15, 10, 3])