In [57]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista 

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
minha_matriz = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [15]:
arr = np.zeros((5, 5))

In [16]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.linspace(0, 15, 2)

array([ 0., 15.])

In [28]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
np.random.rand(5)

array([0.34870784, 0.50734543, 0.47925101, 0.36059105, 0.21246327])

In [32]:
np.random.rand(5, 4)

array([[0.7828269 , 0.02971256, 0.67651584, 0.88560973],
       [0.44410612, 0.87821074, 0.96172721, 0.38216616],
       [0.26034159, 0.30411723, 0.06123597, 0.45030994],
       [0.3349359 , 0.89079463, 0.2836821 , 0.77000984],
       [0.55843259, 0.90779924, 0.37105895, 0.75887321]])

In [35]:
np.random.randint(0, 100, 10)

array([28, 18, 64, 50, 47, 86, 23,  5, 45,  0], dtype=int32)

In [36]:
np.round(np.random.rand(5)*100, 0)

array([83., 72.,  8., 82., 66.])

In [72]:
arr = np.random.rand(5,5)

In [39]:
arr

array([0.39642298, 0.11288266, 0.00675926, 0.15632835, 0.86572894])

In [67]:
arr.reshape((5, 5))

array([[0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605],
       [0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133],
       [0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621],
       [0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493],
       [0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678]])

In [68]:
arr

array([0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605,
       0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133,
       0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621,
       0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493,
       0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678])

In [69]:
arr.reshape((5, 5))

array([[0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605],
       [0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133],
       [0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621],
       [0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493],
       [0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678]])

In [70]:
arr

array([0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605,
       0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133,
       0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621,
       0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493,
       0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678])

In [73]:
arr.shape

(5, 5)

In [74]:
arr.max()

np.float64(0.9912101673353907)

In [75]:
arr.min()

np.float64(0.0039939356824453265)

In [76]:
arr.argmax()

np.int64(12)

In [77]:
arr.argmin()

np.int64(6)

In [2]:
import numpy as np

In [5]:
arr = np.arange(0, 30, 3)

In [6]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[3]

np.int64(9)

In [9]:
arr[2:5]

array([ 6,  9, 12])

In [10]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [11]:
arr[2:27]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
arr[2:] = 100

In [13]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr = np.arange(50).reshape((5, 10))

In [17]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr.shape

(5, 10)

In [19]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr2 = arr[:3]

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
arr2[:] = 100

In [25]:
arr2 = arr[:3].copy()

In [26]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [27]:
arr2[:] = 10

In [28]:
arr2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [33]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [34]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [35]:
arr > (50)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [38]:
bol = arr > 50

In [40]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [41]:
array = np.linspace(0, 100, 30)

In [42]:
array.shape

(30,)

In [45]:
array = array.reshape(3, 10)

In [46]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [47]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

In [48]:
#Exercicios aula 23 - Numpy 

In [3]:
import numpy as np #importando numpy para np

In [52]:
np.zeros(10) #criando uma matriz de 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(10) #criando uma matriz de 10 ones 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.arange(10, 51) #array de numeros inteiros de 10 a 50

In [16]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(10, 51, 2) #array de numeros pares de 10 a 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
minha_matriz = [(0,1,2), (3,4,5), (6,7,8)] #criando matriz 3x3 de 0 a 8

In [67]:
np.array(minha_matriz)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.eye(3) #matriz identidade 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.random.rand(1) #numero aleatório entre 0 e 1

array([0.2769055])

In [87]:
np.random.rand(25) #25 numeros aleatórios de uma distribuição normal

array([0.7751387 , 0.33510321, 0.3096567 , 0.1635566 , 0.50322717,
       0.38128829, 0.90851295, 0.61905476, 0.61301386, 0.93160043,
       0.33706018, 0.06440054, 0.52887511, 0.42659682, 0.12181664,
       0.63537735, 0.81970312, 0.02142095, 0.07715438, 0.53416391,
       0.22488086, 0.32808373, 0.98848005, 0.12109996, 0.81910377])

In [19]:
arr = np.arange(1,101).reshape((10, 10)) / 10 #Matriz pedida 

In [20]:
arr

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [13]:
arr = np.linspace(0, 1, 20) #matriz 20 com espaços entre o 0 e 1 

In [14]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [21]:
mat = np.arange(1, 26).reshape(5,5)

In [22]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
mat[3,4]

np.int64(20)

In [27]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [28]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [29]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat.sum() #soma de todos os valores 

np.int64(325)

In [31]:
mat.std() #desvio padrão dos valores em mat

np.float64(7.211102550927978)

In [33]:
mat.sum(axis=0) #soma de todas as colunas em mat 

array([55, 60, 65, 70, 75])

In [34]:
#Analise de dados - Panda