<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Classifica%C3%A7%C3%A3o_Bin%C3%A1ria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Brest Cancer simples

In [1]:
import pandas as pd

In [2]:
#previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000


In [3]:
# class
y = pd.read_csv('/content/saidas_breast.csv')
y

,0
0,0
1,0
2,0
3,0
4,0
...,...
564,0
565,0
566,0
567,0


In [4]:
import sklearn
from sklearn.model_selection import train_test_split

In [5]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [6]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [7]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [8]:
#Criação da estrutura da Rede Neural
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [9]:
(30 + 1) / 2

15.5

In [28]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer= 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation= 'sigmoid')
])

In [11]:
30 * 16, 496 - 480, 30 * 16 + 16 #Bias

(480, 16, 496)

In [12]:
496 + 17

513

In [29]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
426 / 10

42.6

In [30]:
otimizador = tf.keras.optimizers.Adam(learning_rate= 0.001, clipvalue = 0.5)

In [31]:
rede_neural.compile(optimizer = otimizador , loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [32]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6479 - loss: 0.9073   
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7347 - loss: 0.4977 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7793 - loss: 0.4709 
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7817 - loss: 0.4680
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7981 - loss: 0.4385 
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.3950
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8028 - loss: 0.4696 
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.3735
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8521 - loss: 0.3710
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.5041 
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 

In [35]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-8.41040835e-02, -4.13305372e-01,  1.67748019e-01,
          3.21203113e-01, -2.57564247e-01, -3.54633555e-02,
         -9.74800810e-03,  4.55097184e-02, -1.87658370e-01,
         -2.06449687e-01, -6.46032160e-03,  9.36300233e-02,
          2.72975653e-01, -6.08078064e-03, -2.27423370e-01,
         -1.89542964e-01],
        [-1.19940519e-01, -3.84373069e-01,  1.03073783e-01,
          8.61470774e-02, -2.19424441e-01,  4.06998694e-02,
         -9.83520504e-03,  6.06499761e-02, -2.73123711e-01,
         -2.61363536e-01, -6.44813776e-02,  9.30295214e-02,
          1.39345616e-01, -1.10147908e-01, -2.57071674e-01,
         -1.30309582e-01],
        [-2.96124164e-02, -1.38775274e-01, -2.88606640e-02,
          1.27131656e-01, -8.37205350e-02,  1.56258214e-02,
          1.32942395e-02,  4.25583823e-03,  1.01110414e-02,
          2.44264174e-02,  1.61488615e-02, -3.75520810e-02,
         -6.29283546e-04, -5.21798953e-02, -8.94914120e-02,
         -1.11548081e-01],
        [ 6.2300153

In [36]:
len(pesos0)

2

In [37]:
len(pesos0[1])

16

In [38]:
pesos0[0]

array([[-8.41040835e-02, -4.13305372e-01,  1.67748019e-01,
         3.21203113e-01, -2.57564247e-01, -3.54633555e-02,
        -9.74800810e-03,  4.55097184e-02, -1.87658370e-01,
        -2.06449687e-01, -6.46032160e-03,  9.36300233e-02,
         2.72975653e-01, -6.08078064e-03, -2.27423370e-01,
        -1.89542964e-01],
       [-1.19940519e-01, -3.84373069e-01,  1.03073783e-01,
         8.61470774e-02, -2.19424441e-01,  4.06998694e-02,
        -9.83520504e-03,  6.06499761e-02, -2.73123711e-01,
        -2.61363536e-01, -6.44813776e-02,  9.30295214e-02,
         1.39345616e-01, -1.10147908e-01, -2.57071674e-01,
        -1.30309582e-01],
       [-2.96124164e-02, -1.38775274e-01, -2.88606640e-02,
         1.27131656e-01, -8.37205350e-02,  1.56258214e-02,
         1.32942395e-02,  4.25583823e-03,  1.01110414e-02,
         2.44264174e-02,  1.61488615e-02, -3.75520810e-02,
        -6.29283546e-04, -5.21798953e-02, -8.94914120e-02,
        -1.11548081e-01],
       [ 6.23001531e-02,  8.93363357e

In [40]:
len(pesos0[0])

30

In [41]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[ 0.12740424, -0.01470884,  0.09540726, -0.05133106, -0.04499373,
          0.04238191, -0.15218346, -0.02992122,  0.00304636, -0.11131594,
          0.01479638,  0.11416094, -0.186449  , -0.1135746 ,  0.12175463,
         -0.20003012],
        [ 0.16172332,  0.24110672, -0.00376659, -0.01554768, -0.0039378 ,
          0.15094747,  0.104794  , -0.01127809, -0.02750965,  0.1158377 ,
         -0.00218857, -0.09856465,  0.11151388,  0.30752543, -0.07479248,
         -0.05164405],
        [-0.21058972,  0.41321233,  0.01498056, -0.01789526, -0.07223802,
         -0.04741577,  0.07994135, -0.07658455, -0.00235172,  0.20768291,
         -0.05987078,  0.01224441,  0.03844822,  0.0138152 ,  0.03203773,
         -0.05495207],
        [-0.03112442, -0.06394624,  0.02749593,  0.02862238, -0.04821473,
         -0.06363183, -0.1147263 , -0.02141481, -0.0428625 , -0.18143111,
         -0.03156371,  0.15232266, -0.1628679 , -0.19495168,  0.11308401,
         -0.06372456],
        [ 0.07748418

In [42]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.2550511 ],
        [-0.08174229],
        [-0.35325742],
        [-0.30163267],
        [-0.47854567],
        [ 0.4171982 ],
        [ 0.2287405 ],
        [-0.45437086],
        [-0.04507682],
        [-0.19553757],
        [ 0.006693  ],
        [ 0.27920365],
        [ 0.13607843],
        [ 0.27419013],
        [ 0.20190437],
        [-0.31170568]], dtype=float32),
 array([0.2678655], dtype=float32)]

In [18]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [19]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [20]:
y_teste

,0
129,0
293,1
294,1
295,1
173,1
...,...
261,0
203,0
478,1
331,1


In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [22]:
accuracy_score(y_teste, previsoes)

0.8391608391608392

In [23]:
confusion_matrix(y_teste, previsoes)

array([[25, 21],
       [ 2, 95]])

In [25]:
25 + 95, 21 + 2

(120, 23)

In [26]:
128 / 143, 23 / 143

(0.8951048951048951, 0.16083916083916083)

In [33]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7832 - loss: 2.3575 


[2.3574955463409424, 0.7832167744636536]