In [57]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista 

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
minha_matriz = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [15]:
arr = np.zeros((5, 5))

In [16]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.linspace(0, 15, 2)

array([ 0., 15.])

In [28]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
np.random.rand(5)

array([0.34870784, 0.50734543, 0.47925101, 0.36059105, 0.21246327])

In [32]:
np.random.rand(5, 4)

array([[0.7828269 , 0.02971256, 0.67651584, 0.88560973],
       [0.44410612, 0.87821074, 0.96172721, 0.38216616],
       [0.26034159, 0.30411723, 0.06123597, 0.45030994],
       [0.3349359 , 0.89079463, 0.2836821 , 0.77000984],
       [0.55843259, 0.90779924, 0.37105895, 0.75887321]])

In [35]:
np.random.randint(0, 100, 10)

array([28, 18, 64, 50, 47, 86, 23,  5, 45,  0], dtype=int32)

In [36]:
np.round(np.random.rand(5)*100, 0)

array([83., 72.,  8., 82., 66.])

In [72]:
arr = np.random.rand(5,5)

In [39]:
arr

array([0.39642298, 0.11288266, 0.00675926, 0.15632835, 0.86572894])

In [67]:
arr.reshape((5, 5))

array([[0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605],
       [0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133],
       [0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621],
       [0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493],
       [0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678]])

In [68]:
arr

array([0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605,
       0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133,
       0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621,
       0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493,
       0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678])

In [69]:
arr.reshape((5, 5))

array([[0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605],
       [0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133],
       [0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621],
       [0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493],
       [0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678]])

In [70]:
arr

array([0.24638043, 0.9706569 , 0.49504956, 0.25691111, 0.58941605,
       0.48434236, 0.59098928, 0.33279743, 0.96153726, 0.50381133,
       0.24712836, 0.59239269, 0.97885937, 0.29194177, 0.08519621,
       0.57523357, 0.757931  , 0.51369439, 0.61224964, 0.50497493,
       0.59928211, 0.97070765, 0.43776698, 0.83167725, 0.27048678])

In [73]:
arr.shape

(5, 5)

In [74]:
arr.max()

np.float64(0.9912101673353907)

In [75]:
arr.min()

np.float64(0.0039939356824453265)

In [76]:
arr.argmax()

np.int64(12)

In [77]:
arr.argmin()

np.int64(6)

In [2]:
import numpy as np

In [5]:
arr = np.arange(0, 30, 3)

In [6]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[3]

np.int64(9)

In [9]:
arr[2:5]

array([ 6,  9, 12])

In [10]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [11]:
arr[2:27]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
arr[2:] = 100

In [13]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr = np.arange(50).reshape((5, 10))

In [17]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr.shape

(5, 10)

In [19]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr2 = arr[:3]

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
arr2[:] = 100

In [25]:
arr2 = arr[:3].copy()

In [26]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [27]:
arr2[:] = 10

In [28]:
arr2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [33]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [34]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [35]:
arr > (50)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [38]:
bol = arr > 50

In [40]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [41]:
array = np.linspace(0, 100, 30)

In [42]:
array.shape

(30,)

In [45]:
array = array.reshape(3, 10)

In [46]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [47]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

In [48]:
#Exercicios aula 23 - Numpy 

In [3]:
import numpy as np #importando numpy para np

In [52]:
np.zeros(10) #criando uma matriz de 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(10) #criando uma matriz de 10 ones 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.arange(10, 51) #array de numeros inteiros de 10 a 50

In [16]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(10, 51, 2) #array de numeros pares de 10 a 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
minha_matriz = [(0,1,2), (3,4,5), (6,7,8)] #criando matriz 3x3 de 0 a 8

In [67]:
np.array(minha_matriz)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.eye(3) #matriz identidade 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.random.rand(1) #numero aleatório entre 0 e 1

array([0.2769055])

In [87]:
np.random.rand(25) #25 numeros aleatórios de uma distribuição normal

array([0.7751387 , 0.33510321, 0.3096567 , 0.1635566 , 0.50322717,
       0.38128829, 0.90851295, 0.61905476, 0.61301386, 0.93160043,
       0.33706018, 0.06440054, 0.52887511, 0.42659682, 0.12181664,
       0.63537735, 0.81970312, 0.02142095, 0.07715438, 0.53416391,
       0.22488086, 0.32808373, 0.98848005, 0.12109996, 0.81910377])

In [19]:
arr = np.arange(1,101).reshape((10, 10)) / 10 #Matriz pedida 

In [20]:
arr

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [13]:
arr = np.linspace(0, 1, 20) #matriz 20 com espaços entre o 0 e 1 

In [14]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [21]:
mat = np.arange(1, 26).reshape(5,5)

In [22]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
mat[3,4]

np.int64(20)

In [27]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [28]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [29]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat.sum() #soma de todos os valores 

np.int64(325)

In [31]:
mat.std() #desvio padrão dos valores em mat

np.float64(7.211102550927978)

In [33]:
mat.sum(axis=0) #soma de todas as colunas em mat 

array([55, 60, 65, 70, 75])

In [34]:
#Analise de dados - Panda

In [ ]:
#Series 

In [12]:
import numpy as np
import pandas as pd

In [13]:
labels = ['a', 'b', 'c']

In [14]:
minha_lista = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a':10, 'b':20, 'c':30}

In [18]:
pd.Series(data:=minha_lista, index:=labels)

a    10
b    20
c    30
dtype: int64

In [19]:
series = pd.Series(data:=minha_lista, index:=labels)

In [21]:
series['b']

np.int64(20)

In [22]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [28]:
ser1 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'CDS', 'Japão'])

In [29]:
ser1

EUA         1
Alemanha    2
CDS         3
Japão       4
dtype: int64

In [30]:
ser2 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'Italia', 'Japão'])

In [31]:
ser2

EUA         1
Alemanha    2
Italia      3
Japão       4
dtype: int64

In [33]:
ser1 + ser2 

EUA         2
Alemanha    4
Italia      6
Japão       8
dtype: int64

In [34]:
#DataFrame - Panda 

In [35]:
import numpy as np
import pandas as pd

In [41]:
np.random.seed(101) #numeros aleatórios

In [46]:
dt = pd.DataFrame(np.random.rand(5, 4), index='A B C D E'.split(), columns= 'W X Y Z'.split())

In [48]:
dt

W         X         Y         Z
A  0.442368  0.877587  0.949264  0.478167
B  0.461119  0.637289  0.324608  0.117578
C  0.051101  0.637659  0.812266  0.670260
D  0.651768  0.424569  0.656595  0.209161
E  0.659925  0.529623  0.748520  0.093757

In [49]:
dt['W'] #colunas dataframe 

A    0.442368
B    0.461119
C    0.051101
D    0.651768
E    0.659925
Name: W, dtype: float64

In [50]:
type(dt['W'])

pandas.Series

In [51]:
type(dt)

pandas.DataFrame

In [52]:
dt[['W', 'Z']]

W         Z
A  0.442368  0.478167
B  0.461119  0.117578
C  0.051101  0.670260
D  0.651768  0.209161
E  0.659925  0.093757

In [53]:
dt.W

A    0.442368
B    0.461119
C    0.051101
D    0.651768
E    0.659925
Name: W, dtype: float64

In [54]:
dt['new'] = dt['W'] + dt['X']

In [55]:
dt

W         X         Y         Z       new
A  0.442368  0.877587  0.949264  0.478167  1.319955
B  0.461119  0.637289  0.324608  0.117578  1.098408
C  0.051101  0.637659  0.812266  0.670260  0.688760
D  0.651768  0.424569  0.656595  0.209161  1.076337
E  0.659925  0.529623  0.748520  0.093757  1.189548

In [59]:
dt.drop('new', axis=1)

W         X         Y         Z
A  0.442368  0.877587  0.949264  0.478167
B  0.461119  0.637289  0.324608  0.117578
C  0.051101  0.637659  0.812266  0.670260
D  0.651768  0.424569  0.656595  0.209161
E  0.659925  0.529623  0.748520  0.093757

In [60]:
dt

W         X         Y         Z       new
A  0.442368  0.877587  0.949264  0.478167  1.319955
B  0.461119  0.637289  0.324608  0.117578  1.098408
C  0.051101  0.637659  0.812266  0.670260  0.688760
D  0.651768  0.424569  0.656595  0.209161  1.076337
E  0.659925  0.529623  0.748520  0.093757  1.189548

In [61]:
dt.drop('new', axis=1, inplace=True)

In [62]:
dt

W         X         Y         Z
A  0.442368  0.877587  0.949264  0.478167
B  0.461119  0.637289  0.324608  0.117578
C  0.051101  0.637659  0.812266  0.670260
D  0.651768  0.424569  0.656595  0.209161
E  0.659925  0.529623  0.748520  0.093757

In [64]:
dt.loc['A', 'W'] #Loc seleção baseados no indices e colunas/seleção de dados 

np.float64(0.4423681315127448)

In [66]:
dt.loc['A']

W    0.442368
X    0.877587
Y    0.949264
Z    0.478167
Name: A, dtype: float64

In [67]:
dt.loc[['A', 'B'], ['X', 'Y', 'Z']]

X         Y         Z
A  0.877587  0.949264  0.478167
B  0.637289  0.324608  0.117578

In [74]:
dt.iloc[1:4, 2:] #iloc elementos baseados usados no Numpy 

Y         Z
B  0.324608  0.117578
C  0.812266  0.670260
D  0.656595  0.209161

In [75]:
#DataFrame - Panda 

In [77]:
import pandas as pd
import numpy as np

In [98]:
from numpy.random import rand
np.random.rand(101)

array([9.37088268e-01, 9.49030522e-02, 2.31057176e-01, 4.41994850e-04,
       5.13180544e-01, 8.04203184e-01, 3.90479053e-01, 2.94273120e-01,
       4.28404607e-01, 4.44658141e-01, 9.52941511e-01, 1.62771104e-02,
       2.57061370e-01, 5.00265247e-03, 5.32258223e-01, 7.78800446e-01,
       8.38718068e-01, 9.15557643e-01, 3.62690738e-01, 5.28839592e-01,
       8.24216577e-01, 7.52651473e-01, 3.35359402e-01, 6.96771988e-01,
       8.83341843e-01, 6.02312726e-02, 6.55754521e-01, 3.43685664e-01,
       3.15371715e-01, 9.00184285e-01, 3.40431043e-01, 9.74590123e-01,
       6.83882314e-01, 5.79043231e-01, 9.90305423e-01, 2.31493798e-01,
       6.77571261e-02, 4.42317508e-02, 8.93900641e-01, 7.28230652e-01,
       7.16838306e-01, 7.73181842e-01, 7.57198463e-01, 7.51904294e-02,
       4.23498540e-01, 3.90335978e-01, 4.80777225e-01, 5.81630714e-01,
       4.32152693e-02, 9.39415087e-01, 5.94000682e-01, 3.80590973e-01,
       9.95207806e-01, 2.94175915e-01, 2.43823468e-01, 9.80561991e-01,
      

In [97]:
dt = pd.DataFrame(np.random.rand(5, 4), index='A B C D E'.split(), columns= 'W X Y Z'.split())

In [99]:
dt

W         X         Y         Z
A  0.682120  0.464807  0.397042  0.102317
B  0.027049  0.444853  0.623975  0.324170
C  0.551905  0.691702  0.039997  0.643037
D  0.842524  0.768715  0.066519  0.369285
E  0.498774  0.401972  0.184041  0.896428

In [100]:
dt > 0 #valor booleanos

W     X     Y     Z
A  True  True  True  True
B  True  True  True  True
C  True  True  True  True
D  True  True  True  True
E  True  True  True  True

In [101]:
bol = dt > 0

In [102]:
dt[bol]

W         X         Y         Z
A  0.682120  0.464807  0.397042  0.102317
B  0.027049  0.444853  0.623975  0.324170
C  0.551905  0.691702  0.039997  0.643037
D  0.842524  0.768715  0.066519  0.369285
E  0.498774  0.401972  0.184041  0.896428

In [105]:
dt[dt['W']>0]

W         X         Y         Z
A  0.682120  0.464807  0.397042  0.102317
B  0.027049  0.444853  0.623975  0.324170
C  0.551905  0.691702  0.039997  0.643037
D  0.842524  0.768715  0.066519  0.369285
E  0.498774  0.401972  0.184041  0.896428

In [107]:
dt[dt['W'] >0]['Y']

A    0.397042
B    0.623975
C    0.039997
D    0.066519
E    0.184041
Name: Y, dtype: float64

In [109]:
bol = dt['W'] > 0
dt2 = dt[bol]
dt2['Y']

A    0.397042
B    0.623975
C    0.039997
D    0.066519
E    0.184041
Name: Y, dtype: float64

In [113]:
dt[(dt['W']>0) | (dt['Y']>1)]

W         X         Y         Z
A  0.682120  0.464807  0.397042  0.102317
B  0.027049  0.444853  0.623975  0.324170
C  0.551905  0.691702  0.039997  0.643037
D  0.842524  0.768715  0.066519  0.369285
E  0.498774  0.401972  0.184041  0.896428

In [118]:
dt.reset_index(inplace=True)

In [119]:
dt

index         W         X         Y         Z
0     A  0.682120  0.464807  0.397042  0.102317
1     B  0.027049  0.444853  0.623975  0.324170
2     C  0.551905  0.691702  0.039997  0.643037
3     D  0.842524  0.768715  0.066519  0.369285
4     E  0.498774  0.401972  0.184041  0.896428

In [120]:
col = 'RS RJ MG AM SP'.split()

In [121]:
col

['RS', 'RJ', 'MG', 'AM', 'SP']

In [122]:
dt['Estado'] = col

In [123]:
dt

index         W         X         Y         Z Estado
0     A  0.682120  0.464807  0.397042  0.102317     RS
1     B  0.027049  0.444853  0.623975  0.324170     RJ
2     C  0.551905  0.691702  0.039997  0.643037     MG
3     D  0.842524  0.768715  0.066519  0.369285     AM
4     E  0.498774  0.401972  0.184041  0.896428     SP

In [127]:
dt.set_index('Estado', inplace=True)

In [128]:
dt

index         W         X         Y         Z
Estado                                              
RS         A  0.682120  0.464807  0.397042  0.102317
RJ         B  0.027049  0.444853  0.623975  0.324170
MG         C  0.551905  0.691702  0.039997  0.643037
AM         D  0.842524  0.768715  0.066519  0.369285
SP         E  0.498774  0.401972  0.184041  0.896428

In [1]:
#DataFrame - Panda 

In [4]:
import numpy as np
import pandas as pd

In [44]:
#niveis de indice 
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [45]:
outside 

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [46]:
inside 

[1, 2, 3, 1, 2, 3]

In [47]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [48]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [49]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [50]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns= ['A', 'B'])

In [51]:
df

A         B
G1 1 -0.280609  0.135466
   2 -1.670485 -0.461737
   3  1.136634  1.096107
G2 1 -1.190816  0.903451
   2  0.860568  0.499826
   3 -0.718106  2.642341

In [54]:
df.loc['G1'].loc[1]

A   -0.280609
B    0.135466
Name: 1, dtype: float64

In [55]:
df.index.names = ['Grupo', 'Numero']

In [56]:
df

A         B
Grupo Numero                    
G1    1      -0.280609  0.135466
      2      -1.670485 -0.461737
      3       1.136634  1.096107
G2    1      -1.190816  0.903451
      2       0.860568  0.499826
      3      -0.718106  2.642341

In [58]:
df.xs('G1') #especificando elementos 

A         B
Numero                    
1      -0.280609  0.135466
2      -1.670485 -0.461737
3       1.136634  1.096107

In [59]:
df.xs(1, level='Numero')

A         B
Grupo                    
G1    -0.280609  0.135466
G2    -1.190816  0.903451

In [60]:
#Dados Ausentes

In [62]:
import numpy as np
import pandas as pd

In [65]:
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]}

In [66]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [67]:
df = pd.DataFrame(d)

In [68]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [70]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [71]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [76]:
df.fillna(value='Ausente')

A        B  C
0      1.0      5.0  1
1      2.0  Ausente  2
2  Ausente  Ausente  3

In [78]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [79]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [91]:
df.fillna(df.mean()) #programa jupyter deu erro "method" não estava sendo aceito

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [92]:
#GroupBy.mkv - Função Pandas 

In [115]:
import pandas as pd
#Cria uma DataFrame
data = {'Empresa':['Goog', 'Goog', 'MSFT', 'MSFT', 'LG', 'LG'],
        'Nome':['Andressa', 'Ana', 'Bruna', 'Charlie', 'Daniel', 'Emilío'],
        'Venda':[200,120,300,124,343,350]}

In [116]:
dt = pd.DataFrame(data)

In [117]:
dt

Empresa      Nome  Venda
0    Goog  Andressa    200
1    Goog       Ana    120
2    MSFT     Bruna    300
3    MSFT   Charlie    124
4      LG    Daniel    343
5      LG    Emilío    350

In [118]:
group = dt.groupby('Empresa')

In [119]:
group

In [122]:
group.sum()

Nome  Venda
Empresa                     
Goog      AndressaAna    320
LG       DanielEmilío    693
MSFT     BrunaCharlie    424

In [129]:
group.describe() #mais utilizado futuramente

Venda                                                        
        count   mean         std    min     25%    50%     75%    max
Empresa                                                              
Goog      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
LG        2.0  346.5    4.949747  343.0  344.75  346.5  348.25  350.0
MSFT      2.0  212.0  124.450793  124.0  168.00  212.0  256.00  300.0

In [130]:
group.count()

Nome  Venda
Empresa             
Goog        2      2
LG          2      2
MSFT        2      2

In [132]:
group.sum()

Nome  Venda
Empresa                     
Goog      AndressaAna    320
LG       DanielEmilío    693
MSFT     BrunaCharlie    424

In [135]:
group = dt.groupby('Nome')

In [137]:
group.sum().loc['Ana']

Empresa    Goog
Venda       120
Name: Ana, dtype: object

In [1]:
#Métodos de junção 

In [2]:
import pandas as pd

In [10]:
df1 = pd.DataFrame ({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

In [11]:
df2 = pd.DataFrame ({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

In [16]:
df3 = pd.DataFrame ({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

In [13]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [14]:
df2

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [17]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [18]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [21]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN   A8   B8   C8   D8   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN   A9   B9   C9   D9   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  A10  B10  C10  D10  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  A11  B11  C11  D11  A11  B11  C11  D11

In [23]:
esquerda = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'],
                       'A': ['A0','A1','A2','A3'],
                       'B': ['B0','B1','B2','B3']})

direita = pd.DataFrame ({'Key': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0','C1','C2','C3'],
                       'D': ['D0','D1','D2','D3']})

In [24]:
esquerda

Key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [25]:
direita 

Key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [26]:
pd.merge(esquerda,direita,how='inner',on='Key')

Key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [32]:
esquerda = pd.DataFrame({'Key1': ['K0', 'K1', 'K2', 'K3'],
                         'Key2': ['K0', 'K1', 'K2', 'K3'],
                       'A': ['A0','A1','A2','A3'],
                       'B': ['B0','B1','B2','B3']})

direita = pd.DataFrame ({'Key1': ['K0', 'K1', 'K2', 'K3'],
                         'Key2': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0','C1','C2','C3'],
                       'D': ['D0','D1','D2','D3']})

In [34]:
pd.merge(esquerda, direita, on=['Key1', 'Key2'])

Key1 Key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K1  A1  B1  C1  D1
2   K2   K2  A2  B2  C2  D2
3   K3   K3  A3  B3  C3  D3

In [36]:
pd.merge(esquerda, direita, how='outer', on=['Key1', 'Key2'])

Key1 Key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K1  A1  B1  C1  D1
2   K2   K2  A2  B2  C2  D2
3   K3   K3  A3  B3  C3  D3

In [37]:
pd.merge(esquerda, direita, how='left', on=['Key1', 'Key2'])

Key1 Key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K1  A1  B1  C1  D1
2   K2   K2  A2  B2  C2  D2
3   K3   K3  A3  B3  C3  D3

In [41]:
esquerda = pd.DataFrame({'A': ['A0','A1','A2'],
                       'B': ['B0','B1','B2']},
                        index=['K0', 'K1', 'K2'])

direita = pd.DataFrame ({'C': ['C0','C2','C3'],
                       'D': ['D0','D2','D3']},
                        index=['K0', 'K2', 'K3'])

In [45]:
esquerda

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [46]:
direita 

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [42]:
esquerda.join(direita)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [44]:
esquerda.join(direita, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [47]:
#Operações.mkv

In [80]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444], 'col3':['abc', 'def', 'ghi', 'xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [51]:
df['col2'].unique()

array([444, 555, 666])

In [52]:
import numpy as np

In [54]:
np.unique(df['col2'])

array([444, 555, 666])

In [55]:
len(df['col2'].unique())

3

In [58]:
df['col2'].nunique()

3

In [59]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [60]:
df[df['col1']>2]

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [61]:
df[(df['col1']>2) & (df['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [69]:
def vezes2(x):
    return x*2

In [70]:
df['col1'].sum()

np.int64(10)

In [72]:
df['col1'].apply(vezes2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [73]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [74]:
df['col1'].apply(lambda x: x*x)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [75]:
del df['col2']

In [76]:
df

col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [77]:
df.columns

Index(['col1', 'col3'], dtype='str')

In [78]:
df.index #criação do python

RangeIndex(start=0, stop=4, step=1)

In [83]:
df.sort_values(by='col2', inplace=True)

In [82]:
df #volta ao valor original 

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [84]:
df #inplace mantem ele ordenado

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [87]:
df.dropna()

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [93]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                  'col2':[np.nan,555,666,444],
                  'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [94]:
df['col1'].fillna(value=df['col1'].mean())

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64